### ISSUE TITLE
busco singularity image issue

### ISSUE THREAD

**Issue by mason-linscott** [esolares/HapSolo#8]
Hi esolares,

I have been trying to use the singularity image to run the busco analyses required by HapSolo. Perhaps I am unskilled with singularity but the image does not appear to have the functionality out of the box to run busco3.

First, it appears it appears the config.ini file is not suitable for the environment. When I try to run_BUSCO.py on test contig, it fails with the following error.

```
Singularity> run_BUSCO.py -i ptg000003.fasta -m genome -l ../metazoa_odb9 -o test_1
INFO	****************** Start a BUSCO 3.1.0 analysis, current time: 09/21/2022 05:42:53 ******************
INFO	Configuration loaded from /opt/busco-3.0.2/scripts/../config/config.ini
INFO	Init tools...
INFO	Check dependencies...
ERROR	Cannot write to Augustus config path, please make sure you have write permissions to /data/config/
ERROR	BUSCO analysis failed !
ERROR	Check the logs, read the user guide, if you still need technical support, then please contact mailto:support@orthodb.org

Singularity> 
```

When I then change AUGUSTUS_CONFIG_PATH to a config from a local install of busco3, I instead get the following error:

```
Singularity> run_BUSCO.py -i ptg000003.fasta -m genome -l ../metazoa_odb9 -o test_2
INFO	****************** Start a BUSCO 3.1.0 analysis, current time: 09/21/2022 05:46:55 ******************
INFO	Configuration loaded from /opt/busco-3.0.2/scripts/../config/config.ini
INFO	Init tools...
INFO	Check dependencies...
INFO	Check input file...
INFO	To reproduce this run: python /opt/busco-3.0.2/scripts/run_BUSCO.py -i ptg000003.fasta -o test_2 -l ../metazoa_odb9/ -m genome -c 1 -sp fly
INFO	Mode is: genome
INFO	The lineage dataset is: metazoa_odb9 (eukaryota)
INFO	Temp directory is ./tmp/
INFO	****** Phase 1 of 2, initial predictions ******
INFO	****** Step 1/3, current time: 09/21/2022 05:46:55 ******
INFO	Create blast database...
INFO	[makeblastdb]	Building a new DB, current time: 09/21/2022 05:46:55
INFO	[makeblastdb]	New DB name:   /mnt/ceph/mlinscott/DEEP/hapsolo/test/tmp/test_2_2457583503
INFO	[makeblastdb]	New DB title:  ptg000003.fasta
INFO	[makeblastdb]	Sequence type: Nucleotide
INFO	[makeblastdb]	Keep Linkouts: T
INFO	[makeblastdb]	Keep MBits: T
INFO	[makeblastdb]	Maximum file size: 1000000000B
INFO	[makeblastdb]	Adding sequences from FASTA; added 1 sequences in 0.00962996 seconds.
INFO	[makeblastdb]	1 of 1 task(s) completed at 09/21/2022 05:46:55
INFO	Running tblastn, writing output to /mnt/ceph/mlinscott/DEEP/hapsolo/test/run_test_2/blast_output/tblastn_test_2.tsv...
INFO	[tblastn]	1 of 1 task(s) completed at 09/21/2022 05:46:57
INFO	****** Step 2/3, current time: 09/21/2022 05:46:57 ******
INFO	Maximum number of candidate contig per BUSCO limited to: 3
INFO	Getting coordinates for candidate regions...
INFO	Pre-Augustus scaffold extraction...
INFO	Running Augustus prediction using fly as species:
INFO	[augustus]	Please find all logs related to Augustus errors here: /mnt/ceph/mlinscott/DEEP/hapsolo/test/run_test_2/augustus_output/augustus.log
INFO	[augustus]	1 of 1 task(s) completed at 09/21/2022 05:46:59
INFO	Extracting predicted proteins...
INFO	****** Step 3/3, current time: 09/21/2022 05:46:59 ******
INFO	Running HMMER to confirm orthology of predicted proteins:
CRITICAL	Unhandled exception occurred: ['Traceback (most recent call last):\n', '  File "/opt/busco-3.0.2/scripts/run_BUSCO.py", line 169, in main\n    analysis.run_analysis()\n', '  File "/mnt/ceph/mlinscott/.local/lib/python2.7/site-packages/busco/GenomeAnalysis.py", line 96, in run_analysis\n    self._run_hmmer()\n', '  File "/mnt/ceph/mlinscott/.local/lib/python2.7/site-packages/busco/GenomeAnalysis.py", line 977, in _run_hmmer\n    self.mainout)\n', "OSError: [Errno 2] No such file or directory: '/mnt/ceph/mlinscott/DEEP/hapsolo/test/run_test_2/augustus_output/extracted_proteins'\n"]
[ptg000003.fasta.txt](https://github.com/esolares/HapSolo/files/9616743/ptg000003.fasta.txt)

ERROR	BUSCO analysis failed !
ERROR	Check the logs, read the user guide, if you still need technical support, then please contact mailto:support@orthodb.org

```

When I run busco from singularity on my individual contigs about 40% of them fail due to the same error.

I can confirm that buscov5 works fine on the test contig and that it contains no special characters.

I have attached the contig for your testing if it helps.

All the best,
Mason

**Comment by mason-linscott** [comment]
[ptg000003.fasta.txt](https://github.com/esolares/HapSolo/files/9616778/ptg000003.fasta.txt)

**Comment by esolares** [comment]
Hi, you aren't supposed to run singularity in shell but instead run it as a container. I have updated the examples in the readme. Perhaps that will solve your issues. Also make sure you point singularity to the correct busco config directory from the config.tar.gz download. You will also need to make sure the odb database is in the proper location.

Please let me know if you still have issues after looking at the new documentation for singularity.
